services:
  cms_db:
    container_name: cms-db
    image: mongo
    restart: always
    networks:
      - backend

  cms_app:
    container_name: cms-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - cms-db
    env_file:
      - .env
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cms-db/cms
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
