spring:
  data:
    mongodb:
      uri: mongodb://localhost/cms
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: "21bc445aab2b40"
    password: ${SMTP_PASSWORD}
  main:
    lazy-initialization: true

graphiql:
  cdn:
    enabled: true
    version: latest

server:
  error:
    include-exception: false
    include-stacktrace: never

application:
  mail:
    to: "kontakt@maciejkopec.pl"
    subject: "[Homepage] Mail from: "
  recaptcha-secret: ${GOOGLE_RECAPTCHA_SECRET}
  allowed-origins: "http://localhost:8000,http://localhost"
  api-key: ${API_KEY}
